networks:
  public_net:
    driver: bridge
    driver_opts: {com.docker.network.bridge.name: oai-slice1}
    ipam:
      config:
      - {subnet: 192.168.4.0/24}
    name: demo-oai-public-net-slice1
  public_net_access:
    driver_opts: {com.docker.network.bridge.name: access-slice1}
    ipam:
      config:
      - {subnet: 192.168.6.0/24}
    name: oai-public-access-slice1
  public_net_core:
    driver_opts: {com.docker.network.bridge.name: core-slice1}
    ipam:
      config:
      - {subnet: 192.168.7.0/24}
    name: oai-public-core-slice1
services:
  mysql-slice1:
    container_name: mysql-slice1
    environment: [TZ=Europe/Paris, MYSQL_DATABASE=oai_db, MYSQL_USER=test, MYSQL_PASSWORD=test,
      MYSQL_ROOT_PASSWORD=linux]
    healthcheck: {interval: 10s, retries: 30, test: /bin/bash -c "/tmp/mysql-healthcheck.sh",
      timeout: 5s}
    image: mysql:8.0
    networks:
      public_net: {ipv4_address: 192.168.4.131}
    volumes: ['./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql', './healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh']
  oai-amf-slice1:
    container_name: oai-amf-slice1
    depends_on: [mysql-slice1, vpp-upf-slice1, oai-ausf-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, MCC=208, MNC=95, REGION_ID=128, AMF_SET_ID=1, SERVED_GUAMI_MCC_0=208,
      SERVED_GUAMI_MNC_0=95, SERVED_GUAMI_REGION_ID_0=128, SERVED_GUAMI_AMF_SET_ID_0=1,
      SERVED_GUAMI_MCC_1=460, SERVED_GUAMI_MNC_1=11, SERVED_GUAMI_REGION_ID_1=10,
      SERVED_GUAMI_AMF_SET_ID_1=1, PLMN_SUPPORT_MCC=208, PLMN_SUPPORT_MNC=95, PLMN_SUPPORT_TAC=0xa000,
      SST_0=222, SD_0=123, SST_1=128, SD_1=12, AMF_INTERFACE_NAME_FOR_NGAP=eth0, AMF_INTERFACE_NAME_FOR_N11=eth0,
      SMF_INSTANCE_ID_0=1, SMF_FQDN_0=oai-smf-slice1, SMF_IPV4_ADDR_0=192.168.4.133,
      SELECTED_0=true, NF_REGISTRATION=yes, SMF_SELECTION=yes, USE_FQDN_DNS=yes, EXTERNAL_AUSF=yes,
      EXTERNAL_UDM=no, EXTERNAL_NSSF=no, NRF_IPV4_ADDRESS=192.168.4.130, NRF_FQDN=oai-nrf-slice1,
      AUSF_IPV4_ADDRESS=192.168.4.138, AUSF_FQDN=oai-ausf-slice1, UDM_IPV4_ADDRESS=192.168.4.137,
      UDM_FQDN=oai-udm-slice1, 'INT_ALGO_LIST=["NIA1" , "NIA2"]', 'CIPH_ALGO_LIST=["NEA1"
        , "NEA2"]']
    image: oaisoftwarealliance/oai-amf:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.132}
  oai-ausf-slice1:
    container_name: oai-ausf-slice1
    depends_on: [oai-udm-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, AUSF_NAME=OAI_AUSF, SBI_IF_NAME=eth0, USE_FQDN_DNS=yes,
      REGISTER_NRF=yes, UDM_IP_ADDRESS=192.168.4.137, UDM_FQDN=oai-udm-slice1, NRF_IPV4_ADDRESS=192.168.4.130,
      NRF_FQDN=oai-nrf-slice1]
    image: oaisoftwarealliance/oai-ausf:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.138}
  oai-nrf-slice1:
    container_name: oai-nrf-slice1
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, NRF_INTERFACE_NAME_FOR_SBI=eth0]
    image: oaisoftwarealliance/oai-nrf:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.130}
  oai-smf-slice1:
    container_name: oai-smf-slice1
    depends_on: [oai-amf-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, SMF_INTERFACE_NAME_FOR_N4=eth0, SMF_INTERFACE_NAME_FOR_SBI=eth0,
      DEFAULT_DNS_IPV4_ADDRESS=132.21.3.100, DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8,
      AMF_IPV4_ADDRESS=192.168.4.132, AMF_FQDN=oai-amf-slice1, UDM_IPV4_ADDRESS=192.168.4.137,
      UDM_FQDN=oai-udm-slice1, UPF_IPV4_ADDRESS=192.168.4.201, UPF_FQDN_0=vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org,
      NRF_IPV4_ADDRESS=192.168.4.130, NRF_FQDN=oai-nrf-slice1, DEFAULT_CSCF_IPV4_ADDRESS=127.0.0.1,
      USE_LOCAL_SUBSCRIPTION_INFO=yes, REGISTER_NRF=yes, DISCOVER_UPF=yes, USE_FQDN_DNS=yes,
      ENABLE_USAGE_REPORTING=yes, DNN_NI0=oai, TYPE0=IPv4, DNN_RANGE0=12.1.1.151 -
        12.1.1.253, NSSAI_SST0=1, SESSION_AMBR_UL0=200Mbps, SESSION_AMBR_DL0=300Mbps,
      DNN_NI1=oai.ipv4, TYPE1=IPv4, DNN_RANGE1=12.1.1.51 - 12.1.1.150, NSSAI_SST1=1,
      NSSAI_SD1=1, SESSION_AMBR_UL1=100Mbps, SESSION_AMBR_DL1=200Mbps, DNN_NI2=default,
      TYPE2=IPv4, DNN_RANGE2=12.1.1.2 - 12.1.1.50, NSSAI_SST2=222, NSSAI_SD2=123,
      SESSION_AMBR_UL2=50Mbps, SESSION_AMBR_DL2=100Mbps, DNN_NI3=ims, TYPE3=IPv4v6,
      DNN_RANGE3=14.1.1.2 - 14.1.1.253]
    extra_hosts: ['vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org:192.168.4.201']
    image: oaisoftwarealliance/oai-smf:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.133}
  oai-udm-slice1:
    container_name: oai-udm-slice1
    depends_on: [oai-udr-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, UDM_NAME=OAI_UDM, SBI_IF_NAME=eth0, REGISTER_NRF=yes,
      USE_FQDN_DNS=yes, UDR_IP_ADDRESS=192.168.4.136, UDR_FQDN=oai-udr-slice1, NRF_IPV4_ADDRESS=192.168.4.130,
      NRF_FQDN=oai-nrf-slice1]
    image: oaisoftwarealliance/oai-udm:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.137}
  oai-udr-slice1:
    container_name: oai-udr-slice1
    depends_on: [mysql-slice1, oai-nrf-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [TZ=Europe/Paris, UDR_NAME=OAI_UDR, UDR_INTERFACE_NAME_FOR_NUDR=eth0,
      MYSQL_IPV4_ADDRESS=192.168.4.131, MYSQL_USER=test, MYSQL_PASS=test, MYSQL_DB=oai_db,
      WAIT_MYSQL=120, USE_FQDN_DNS=yes, REGISTER_NRF=yes, NRF_IPV4_ADDRESS=192.168.4.130,
      NRF_FQDN=oai-nrf-slice1]
    image: oaisoftwarealliance/oai-udr:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.136}
  vpp-upf-slice1:
    container_name: vpp-upf-slice1
    depends_on: [oai-nrf-slice1]
    deploy:
      resources:
        limits: {cpus: '0.25', memory: 1G}
        reservations: {memory: 0.5G}
    environment: [IF_1_IP=192.168.4.201, IF_1_TYPE=N4, IF_2_IP=192.168.6.201, IF_2_TYPE=N3,
      IF_2_NWI=access.oai.org, IF_3_IP=192.168.7.201, IF_3_TYPE=N6, IF_3_IP_REMOTE=192.168.7.135,
      IF_3_NWI=internet.oai.org, NAME=VPP-UPF, MNC=95, MCC=208, REALM=3gppnetwork.org,
      VPP_MAIN_CORE=0, VPP_CORE_WORKER=1, VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/,
      SNSSAI_SD=123, SNSSAI_SST=222, DNN=default, REGISTER_NRF=yes, NRF_IP_ADDR=192.168.4.130,
      NRF_PORT=80, HTTP_VERSION=1]
    healthcheck: {interval: 10s, retries: 5, test: /bin/bash -c "pgrep vpp", timeout: 5s}
    image: oaisoftwarealliance/oai-upf-vpp:v1.5.0
    networks:
      public_net: {ipv4_address: 192.168.4.134}
      public_net_access: {ipv4_address: 192.168.6.134}
      public_net_core: {ipv4_address: 192.168.7.134}
    privileged: true
version: '3.8'
