# *************************************************************
# *                         ${slice_name}                            *
# *************************************************************
# 修改部分：SNSSAI_SD=123，SNSSAI_SST=222，容器名以${slice_name}结尾，镜像标签v1.5.0
# 网段统一修改为10，12，13网段

#*****************************更新日志: v1.01**********************************
#日期：20230625
#内容：  1. 删除oai-ext-dn容器      2.增加控制cpu和内存的参数
#备注： 含有cpu及内存限制的docker-compose在启动时需要添加参数： docker-compose --compatibility -f xxx.yaml up -d
#*******************************************************************************

version: '3.8'
services:
    mysql-${slice_name}:
        container_name: "mysql-${slice_name}"
        image: mysql:8.0
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: ${ip_oai}131
    oai-udr-${slice_name}:
        container_name: "oai-udr-${slice_name}"
        image: oaisoftwarealliance/oai-udr:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_udr}
              memory: ${limit_memory_udr}
            reservations:
              memory: ${reservations_memory_udr}
        environment:
        - TZ=Europe/Paris
        - UDR_NAME=OAI_UDR
        - UDR_INTERFACE_NAME_FOR_NUDR=eth0
        - MYSQL_IPV4_ADDRESS=${ip_oai}131
        - MYSQL_USER=test
        - MYSQL_PASS=test
        - MYSQL_DB=oai_db
        - WAIT_MYSQL=120
        - USE_FQDN_DNS=yes
        - REGISTER_NRF=yes
        - NRF_IPV4_ADDRESS=${ip_oai}130
        - NRF_FQDN=oai-nrf-${slice_name}
        depends_on:
            - mysql-${slice_name}
            - oai-nrf-${slice_name}
        networks:
            public_net:
                ipv4_address: ${ip_oai}136
    oai-udm-${slice_name}:
        container_name: "oai-udm-${slice_name}"
        image: oaisoftwarealliance/oai-udm:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_udm}
              memory: ${limit_memory_udm}
            reservations:
              memory: ${reservations_memory_udm}
        environment:
            - TZ=Europe/Paris
            - UDM_NAME=OAI_UDM
            - SBI_IF_NAME=eth0
            - REGISTER_NRF=yes
            - USE_FQDN_DNS=yes
            - UDR_IP_ADDRESS=${ip_oai}136
            - UDR_FQDN=oai-udr-${slice_name}
            - NRF_IPV4_ADDRESS=${ip_oai}130
            - NRF_FQDN=oai-nrf-${slice_name}
        depends_on:
            - oai-udr-${slice_name}
        networks:
            public_net:
                ipv4_address: ${ip_oai}137
    oai-ausf-${slice_name}:
        container_name: "oai-ausf-${slice_name}"
        image: oaisoftwarealliance/oai-ausf:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_ausf}
              memory: ${limit_memory_ausf}
            reservations:
              memory: ${reservations_memory_ausf}
        environment:
            - TZ=Europe/Paris
            - AUSF_NAME=OAI_AUSF
            - SBI_IF_NAME=eth0
            - USE_FQDN_DNS=yes
            - REGISTER_NRF=yes
            - UDM_IP_ADDRESS=${ip_oai}137
            - UDM_FQDN=oai-udm-${slice_name}
            - NRF_IPV4_ADDRESS=${ip_oai}130
            - NRF_FQDN=oai-nrf-${slice_name}
        depends_on:
            - oai-udm-${slice_name}
        networks:
            public_net:
                ipv4_address: ${ip_oai}138
    oai-nrf-${slice_name}:
        container_name: "oai-nrf-${slice_name}"
        image: oaisoftwarealliance/oai-nrf:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_nrf}
              memory: ${limit_memory_nrf}
            reservations:
              memory: ${reservations_memory_nrf}
        environment:
            - TZ=Europe/Paris
            - NRF_INTERFACE_NAME_FOR_SBI=eth0
        networks:
            public_net:
                ipv4_address: ${ip_oai}130
    oai-amf-${slice_name}:
        container_name: "oai-amf-${slice_name}"
        image: oaisoftwarealliance/oai-amf:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_amf}
              memory: ${limit_memory_amf}
            reservations:
              memory: ${reservations_memory_amf}
        environment:
            - TZ=Europe/Paris
            - MCC=208
            - MNC=95
            - REGION_ID=128
            - AMF_SET_ID=1
            - SERVED_GUAMI_MCC_0=208
            - SERVED_GUAMI_MNC_0=95
            - SERVED_GUAMI_REGION_ID_0=128
            - SERVED_GUAMI_AMF_SET_ID_0=1
            - SERVED_GUAMI_MCC_1=460
            - SERVED_GUAMI_MNC_1=11
            - SERVED_GUAMI_REGION_ID_1=10
            - SERVED_GUAMI_AMF_SET_ID_1=1
            - PLMN_SUPPORT_MCC=208
            - PLMN_SUPPORT_MNC=95
            - PLMN_SUPPORT_TAC=0xa000
            # Slice 0 (222, 123)
            - SST_0=222
            - SD_0=123
            # Slice 0 (128, 12)
            - SST_1=128
            - SD_1=12
            - AMF_INTERFACE_NAME_FOR_NGAP=eth0
            - AMF_INTERFACE_NAME_FOR_N11=eth0
            # One single SMF instance
            - SMF_INSTANCE_ID_0=1
            - SMF_FQDN_0=oai-smf-${slice_name}
            - SMF_IPV4_ADDR_0=${ip_oai}133
            - SELECTED_0=true
            - NF_REGISTRATION=yes
            - SMF_SELECTION=yes
            - USE_FQDN_DNS=yes
            - EXTERNAL_AUSF=yes
            - EXTERNAL_UDM=no
            - EXTERNAL_NSSF=no
            - NRF_IPV4_ADDRESS=${ip_oai}130
            - NRF_FQDN=oai-nrf-${slice_name}
            - AUSF_IPV4_ADDRESS=${ip_oai}138
            - AUSF_FQDN=oai-ausf-${slice_name}
            - UDM_IPV4_ADDRESS=${ip_oai}137
            - UDM_FQDN=oai-udm-${slice_name}
            - INT_ALGO_LIST=["NIA1" , "NIA2"]
            - CIPH_ALGO_LIST=["NEA1" , "NEA2"]
        depends_on:
            - mysql-${slice_name}
            - vpp-upf-${slice_name}
            - oai-ausf-${slice_name}
        networks:
            public_net:
                ipv4_address: ${ip_oai}132
    oai-smf-${slice_name}:
        container_name: "oai-smf-${slice_name}"
        image: oaisoftwarealliance/oai-smf:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_smf}
              memory: ${limit_memory_smf}
            reservations:
              memory: ${reservations_memory_smf}
        environment:
            - TZ=Europe/Paris
            - SMF_INTERFACE_NAME_FOR_N4=eth0
            - SMF_INTERFACE_NAME_FOR_SBI=eth0
            - DEFAULT_DNS_IPV4_ADDRESS=132.21.3.100
            - DEFAULT_DNS_SEC_IPV4_ADDRESS=8.8.8.8
            - AMF_IPV4_ADDRESS=${ip_oai}132
            - AMF_FQDN=oai-amf-${slice_name}
            - UDM_IPV4_ADDRESS=${ip_oai}137
            - UDM_FQDN=oai-udm-${slice_name}
            - UPF_IPV4_ADDRESS=${ip_oai}201
            - UPF_FQDN_0=vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org
            - NRF_IPV4_ADDRESS=${ip_oai}130
            - NRF_FQDN=oai-nrf-${slice_name}
            - DEFAULT_CSCF_IPV4_ADDRESS=127.0.0.1  # only needed when ims is being used
            - USE_LOCAL_SUBSCRIPTION_INFO=yes  #Set to yes if SMF uses local subscription information instead of from an UDM
            - REGISTER_NRF=yes
            - DISCOVER_UPF=yes
            - USE_FQDN_DNS=yes
            - ENABLE_USAGE_REPORTING=yes
            # Slice 0 (1, 0xFFFFFF)
            - DNN_NI0=oai
            - TYPE0=IPv4
            - DNN_RANGE0=12.1.1.151 - 12.1.1.253
            - NSSAI_SST0=1
            - SESSION_AMBR_UL0=200Mbps
            - SESSION_AMBR_DL0=300Mbps
            # Slice 1 (1, 1)
            - DNN_NI1=oai.ipv4
            - TYPE1=IPv4
            - DNN_RANGE1=12.1.1.51 - 12.1.1.150
            - NSSAI_SST1=1
            - NSSAI_SD1=1
            - SESSION_AMBR_UL1=100Mbps
            - SESSION_AMBR_DL1=200Mbps
            # Slice 2 (222, 123)
            - DNN_NI2=default
            - TYPE2=IPv4
            - DNN_RANGE2=12.1.1.2 - 12.1.1.50
            - NSSAI_SST2=222
            - NSSAI_SD2=123
            - SESSION_AMBR_UL2=50Mbps
            - SESSION_AMBR_DL2=100Mbps
            # Slice 3 for ims
            - DNN_NI3=ims
            - TYPE3=IPv4v6
            - DNN_RANGE3=14.1.1.2 - 14.1.1.253
        extra_hosts:
            - "vpp-upf.node.5gcn.mnc95.mcc208.3gppnetwork.org:${ip_oai}201"
        depends_on:
            - oai-amf-${slice_name}
        networks:
            public_net:
                ipv4_address: ${ip_oai}133
    vpp-upf-${slice_name}:
        privileged: true
        container_name: "vpp-upf-${slice_name}"
        image: oaisoftwarealliance/oai-upf-vpp:v1.5.0
        deploy:
          resources:
            limits:
              cpus: ${limit_cpu_upf}
              memory: ${limit_memory_upf}
            reservations:
              memory: ${reservations_memory_upf}
        environment:
            - IF_1_IP=${ip_oai}201
            - IF_1_TYPE=N4
            - IF_2_IP=${ip_access}201
            - IF_2_TYPE=N3
            - IF_2_NWI=access.oai.org
            - IF_3_IP=${ip_core}201
            - IF_3_TYPE=N6
            - IF_3_IP_REMOTE=${ip_core}135 # EXT-DN IP Address
            - IF_3_NWI=internet.oai.org
            - NAME=VPP-UPF
            - MNC=95
            - MCC=208
            - REALM=3gppnetwork.org
            - VPP_MAIN_CORE=0
            - VPP_CORE_WORKER=1
#           - VPP_PLUGIN_PATH=/usr/lib64/vpp_plugins/                # RHEL7
            - VPP_PLUGIN_PATH=/usr/lib/x86_64-linux-gnu/vpp_plugins/ # Ubntu18.04
            - SNSSAI_SD=123
            - SNSSAI_SST=222
            - DNN=default
            - REGISTER_NRF=yes
            - NRF_IP_ADDR=${ip_oai}130
            - NRF_PORT=80
            - HTTP_VERSION=1
        depends_on:
            - oai-nrf-${slice_name}
        healthcheck:
            test: /bin/bash -c "pgrep vpp"
            interval: 10s
            timeout: 5s
            retries: 5
        networks:
            public_net:
                ipv4_address: ${ip_oai}134
            public_net_access:
                ipv4_address: ${ip_access}134
            public_net_core:
                ipv4_address: ${ip_core}134

networks:
    public_net:
        driver: bridge
        name: demo-oai-public-net-${slice_name}
        ipam:
            config:
                - subnet: ${ip_oai}0/24
        driver_opts:
            com.docker.network.bridge.name: "oai-${slice_name}"
    public_net_access:
        name: oai-public-access-${slice_name}
        ipam:
            config:
                - subnet: ${ip_access}0/24
        driver_opts:
            com.docker.network.bridge.name: "access-${slice_name}"
    public_net_core:
        name: oai-public-core-${slice_name}
        ipam:
            config:
                - subnet: ${ip_core}0/24
        driver_opts:
            com.docker.network.bridge.name: "core-${slice_name}"
